import { useEffect, useState } from "react"
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { doc, getDoc } from "firebase/firestore"
import { db } from "../firebase"

import BoxWindow from "../components/BoxWindow"
import BoxActionBar from "../components/BoxActionBar"
import ContentWindow from "../components/ContentWindow"

import { useUserStore } from "../stores/userStore"

export default function Home() {

  const user = useUserStore((state) => state.user)
  
  const [box, setBox] = useState({
    owner: "",
    objects: [],
    scale: 0.4,
    position: {x: 0, y: 0},
  })
  const [currentAction, setCurrentAction] = useState("pan") // turn currentAction into a zustand store, maybe like useSandboxSelectedAction
  const [isShowUserSignup, setIsShowUserSignup] = useState(false)

  useEffect(() => {
    const fetchUser = async () => {
      if (user && !user.username) {
        const docRef = doc(db, "users", user.uid)
        const docSnap = await getDoc(docRef)

        if (docSnap.exists()) {
          const data = docSnap.data()
          console.log("Document data: ", data)
          useUserStore.getState().setUsername(docSnap.data().username)
        } else {
          setIsShowUserSignup(true)
        }
      }

      return () => {
        console.log("unmounted")
      }
    }

    fetchUser()
  }, [user])

  return (
    <div className={styles.container}>
      <Head>
        <title>eternebox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isShowUserSignup ?
        <ContentWindow>
          Hello
        </ContentWindow>
      :
      <>
        <BoxWindow 
          currentAction={currentAction} 
          box={box}
          setBox={setBox}

        />
        <BoxActionBar 
          currentAction={currentAction} 
          setCurrentAction={setCurrentAction} 
          box={box}
          setBox={setBox}
        />
      </>
      }
    </div>
  )
}
