import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/router";
import Head from "next/head";

import { MainContainer } from "../../styles/BoxPage.style";

import BoxView from "../../components/BoxView";
import PropertyBar from "../../components/PropertyBar";
import ToolBar from "../../components/ToolBar";

import { useToolStore } from "../../stores/toolStore";

import { listAll, ref, getDownloadURL } from "firebase/storage";
import { doc, getDoc } from "firebase/firestore";
import { db, storage } from "../../firebase";

export default function BoxPage() {
  const selectedTool = useToolStore((state) => state.selectedTool);
  const router = useRouter();
  const { boxId } = router.query;

  const isFirstRender = useRef(true);

  const [box, setBox] = useState({
    owner: boxId,
    background: {
      position: {
        x: 0,
        y: 0,
      },
    },
    objects: [],
    scale: 0.2,
    position: { x: 0, y: 0 },
    selectedObjectId: "",
  });

  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false;
      return;
    }

    if (!boxId) {
      return;
    }

    const getStoredImages = async () => {
      try {
        let imageListRef = ref(storage, `boxes/${boxId}/`);
        let res = await listAll(imageListRef);
        res.items.forEach((item) => {
          console.log(item);
          getDownloadURL(item).then(async (res) => {
            console.log(res);
            const docRef = doc(db, "objects", item.name);
            const docSnap = await getDoc(docRef);
            if (docSnap.exists()) {
              const data = docSnap.data();
              console.log(data);
              let image = new Image();
              image.src = res;
              image.onload = () => {
                setBox((prev) => {
                  return {
                    ...prev,
                    objects: [
                      ...prev.objects,
                      {
                        id: data.id,
                        src: res,
                        position: {
                          x: data.position.x,
                          y: data.position.y,
                        },
                        width: data.width,
                        height: data.height,
                        index: prev.objects.length,
                        type: data.type,
                      },
                    ],
                  };
                });
              };
            } else {
              console.log("No such document");
            }
          });
        });
      } catch (err) {
        console.log(err);
      }
    };

    getStoredImages();

    return () => {
      setBox((prev) => {
        return {
          ...prev,
          owner: boxId,
          objects: [],
        };
      });
    };
  }, [boxId]);

  return (
    <MainContainer toolbar={true}>
      <Head>
        <title>eternebox</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <BoxView box={box} setBox={setBox} />
        <PropertyBar
          box={box}
          setBox={setBox}
          show={selectedTool === "customize-box" ? true : false}
        />
        <ToolBar
          box={box}
          setBox={setBox}
          show={selectedTool === "customize-box" ? true : false}
        />
      </>
    </MainContainer>
  );
}
